# Generated by Django 6.0.3 on 2026-03-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GunlukAktivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=50)),
                ('tarih', models.DateField()),
                ('toplam_adim', models.IntegerField(default=0)),
                ('excited_count', models.IntegerField(default=0)),
                ('ortalama_mag', models.FloatField(default=0)),
                ('max_mag', models.FloatField(default=0)),
                ('gece_adim', models.IntegerField(default=0)),
                ('kizginlik_skoru', models.FloatField(default=0)),
                ('kizginlik_alarm', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'GunlukAktivite',
                'unique_together': {('mac', 'tarih')},
            },
        ),
    ]
