# Generated by Django 6.0.3 on 2026-03-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gunlukaktivite'),
    ]

    operations = [
        migrations.AddField(
            model_name='gunlukaktivite',
            name='yatma_suresi_dk',
            field=models.IntegerField(default=0),
        ),
    ]
