# Generated by Django 6.0.3 on 2026-03-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gunlukaktivite_yatma_suresi_dk'),
    ]

    operations = [
        migrations.AddField(
            model_name='gunlukaktivite',
            name='lying_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
