# Generated by Django 6.0.3 on 2026-04-02 13:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_gunlukaktivite_lying_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ear_tag', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(default='Female', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Animal',
            },
        ),
        migrations.CreateModel(
            name='Paddock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('capacity', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Paddock',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EXCITED_MAG', models.FloatField(default=25.0)),
                ('WALK_STD_MIN', models.FloatField(default=2.0)),
                ('WALK_STD_MAX', models.FloatField(default=15.0)),
                ('WALK_PEAKS_MIN', models.IntegerField(default=1)),
                ('STILL_STD_MAX', models.FloatField(default=2.0)),
                ('STILL_MAG_MIN', models.FloatField(default=7.5)),
                ('STILL_MAG_MAX', models.FloatField(default=12.5)),
                ('LYING_STILL_MIN_MINUTES', models.IntegerField(default=2)),
                ('LYING_NIGHT_START', models.IntegerField(default=22)),
                ('LYING_NIGHT_END', models.IntegerField(default=6)),
                ('MAG_PEAK_THRESHOLD', models.FloatField(default=11.5)),
                ('MAG_VALLEY_THRESHOLD', models.FloatField(default=9.5)),
                ('COOLDOWN_MS', models.IntegerField(default=650)),
                ('WINDOW_SIZE', models.IntegerField(default=5)),
                ('FETCH_INTERVAL_MS', models.IntegerField(default=700)),
            ],
            options={
                'db_table': 'SystemSettings',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='gunlukaktivite',
            name='last_activity',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='gunlukaktivite',
            name='last_activity_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gunlukaktivite',
            name='still_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accelerometerdata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='device',
            name='animal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='core.animal'),
        ),
        migrations.CreateModel(
            name='Insemination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insemination_date', models.DateTimeField()),
                ('bull_info', models.CharField(blank=True, default='', max_length=200)),
                ('technician', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Sonuç Bekleniyor'), ('SUCCESS', 'Gebe (Başarılı)'), ('FAILED', 'Tutmadı (Başarısız)'), ('CANCELLED', 'İptal Edildi')], default='PENDING', max_length=20)),
                ('pregnancy_check_date', models.DateField(blank=True, null=True)),
                ('expected_calving_date', models.DateField(blank=True, null=True)),
                ('next_heat_expected', models.DateField(blank=True, null=True)),
                ('actual_calving_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inseminations', to='core.animal')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Insemination',
                'ordering': ['-insemination_date'],
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='paddock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='core.paddock'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin (Patron)'), ('VET', 'Veteriner'), ('WORKER', 'İşçi')], max_length=20)),
                ('permission_key', models.CharField(max_length=50)),
                ('is_allowed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'RolePermission',
                'unique_together': {('role', 'permission_key')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin (Patron)'), ('VET', 'Veteriner'), ('WORKER', 'İşçi')], default='WORKER', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserProfile',
            },
        ),
    ]
